services:
  document-collection-backend:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"